twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
    globals:
        mercure_hub: '%env(MERCURE_HUB)%'
        mercure_host: '%env(MERCURE_HOST)%'
    form_themes:
        - '@KMSFroalaEditor/Form/froala_widget.html.twig'